services:

  postgres-events:
    image: postgres:latest
    container_name: postgres-events
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .postgres.env
    volumes:
      - db-events:/var/lib/postgresql/data
    networks:
      - network_db

  events-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-events
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: always
    volumes:
      - images:/data
    networks:
      - network_db            
                                                      
volumes:
  db-events:
    name: db-events       
  images:
    name: images           

networks:
  network_db:
    name: network_db       
    driver: bridge