services:

  postgres-events:
    image: postgres:latest
    container_name: postgres-events
    ports:
      - "7070:5432"
    restart: always
    env_file:
      - .postgres.env
    volumes:
      - db-events:/var/lib/postgresql/data
    networks:
      - network_db

  events-service:
    image: ...
    container_name: events-service
    env_file:
      - .env
    ports:
      - "7007:7007"
    depends_on:
      - postgres-events
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7007"]
    restart: always
    volumes:
      - images:/data
    networks:
      - network_db                                                            
volumes:                                                                    
  db-events:
  images:

networks:
  network_db:
    driver: bridge