"""replace visitors columns

Revision ID: 2693e00fa066
Revises: 40eef4cf5cf3
Create Date: 2025-02-24 19:17:19.407348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2693e00fa066'
down_revision: Union[str, None] = '40eef4cf5cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visitors_email_key', 'visitors', type_='unique')
    op.drop_constraint('visitors_user_id_key', 'visitors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('visitors_user_id_key', 'visitors', ['user_id'])
    op.create_unique_constraint('visitors_email_key', 'visitors', ['email'])
    # ### end Alembic commands ###
