"""add column in news

Revision ID: 057ee679471b
Revises: 143b94ddbfb2
Create Date: 2025-03-30 19:09:45.451567

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '057ee679471b'
down_revision: Union[str, None] = '143b94ddbfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('head', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'head')
    # ### end Alembic commands ###
