name: Events

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

jobs:
    build:
      runs-on: ubuntu-latest


      steps:
        - name: Check repo
          uses: actions/checkout@v4
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: ${{ runner.os }}-pip-
        - name: Install requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run lint
          run:
            ruff check . --config=ruff.toml
        - name: Run tests
          run: |
            pytest -v
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_LOGIN }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
